### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Shraymonks** [Shraymonks/flow-interfaces-chrome#20]

**Comment by ssorallen** [comment]
Tests would be great! Tests were part of my motivation for suggesting #13 since the flow-typed repo requires test and has a standardized way of [writing LibDef tests](https://github.com/flow-typed/flow-typed/wiki/Contributing-Library-Definitions#writing-libdef-tests). They use an `$ExpectError` annotation to mark spots in tests that you expect Flow to return errors.

This repo could maybe hijack the [runTests.js](https://github.com/flow-typed/flow-typed/blob/master/cli/src/commands/runTests.js) script from flow-typed, but their CLI does some work to confirm the test command is only run [in the flow-typed repo](https://github.com/flow-typed/flow-typed/blob/master/cli/src/lib/isInFlowTypedRepo.js).
